version: 2
updates:

  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "release-3.x"
    reviewers:
      - "rangerrick"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
