language: java
sudo: false # faster builds

before_install:
  - pip install --user codecov
  - echo "MAVEN_OPTS=-Xmx1024m" > ~/.mavenrc

after_success:
  - codecov

jdk:
  - oraclejdk8
  - oraclejdk7
